---
baseURL: "/"
languageCode: fr-fr
title: Hugo Ananke Forestry Starter
theme: ananke
DefaultContentLanguage: en
SectionPagesMenu: 
  - footer
  - main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  favicon: ''
  site_logo: ''
  description: The last theme you'll ever need. Maybe.
  facebook: ''
  twitter: https://twitter.com/GoHugoIO
  instagram: ''
  youtube: ''
  github: ''
  gitlab: ''
  linkedin: ''
  mastodon: ''
  slack: ''
  stackoverflow: ''
  rss: ''
  background_color_class: bg-black
  featured_image: "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number: 2
  body_classes: baskerville bg-moon-gray
